### ISSUE TITLE
Document Sablier V1.0 addresses

### ISSUE THREAD

**Issue by PaulRBerg** [sablierhq/docs#13]
Sablier V1.0 is still being tracked by various tools (e.g. Dune Analytics), so it would be helpful to document the Sablier V1.0 addresses in our documentation website.

**Comment by maxdesalle** [comment]
Fixed in [e64a865](https://github.com/sablierhq/docs/commit/e64a86501deeec1f5ab12ae7e1ba454fd648ea9e)! Sorry for it taking so long, completely forgot about this.

**Comment by PaulRBerg** [comment]
no worries, thanks.
